INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Howard the Duck', 110, 'Sci-Fi', 4.6, 'PG');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Lavalantula', 83, 'Horror', 4.7, 'TV-14');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Starship Troopers', 129, 'Sci-Fi', 7.2, 'PG-13');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Waltz With Bashir', 90, 'Documentary', 8.0, 'R');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Spaceballs', 96, 'Comedy', 7.1, 'PG');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Monsters Inc.', 92, 'Animation', 8.1, 'G');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('The Iron Giant', 86, 'Animation', 8.1, 'PG');

INSERT INTO MOVIES (TITLE, RUNTIME, GENRE, IMDB_SCORE, RATING)
VALUES('Girl, Interrupted', 127, 'Drama', 7.3, 'R');

SELECT * FROM MOVIES
WHERE GENRE IS 'Sci-Fi';

SELECT * FROM MOVIES
WHERE RATING IS 'G'
OR RATING IS 'PG'
AND RUNTIME <100;

SELECT * FROM MOVIES
WHERE IMDB_SCORE <7.5
GROUP BY GENRE, ID;

UPDATE MOVIES
SET RATING = 'R'
WHERE TITLE IS 'Starship Troopers';

SELECT ID, RATING FROM MOVIES
WHERE GENRE IS 'Horror' OR GENRE IS 'Documentary';

SELECT AVG(IMDB_SCORE), MAX(IMDB_SCORE), MIN(IMDB_SCORE), RATING
FROM MOVIES
GROUP BY RATING;



